### ISSUE TITLE
Spoutcam not showing up on the Mediapipe container

### ISSUE THREAD

**Issue by tasos-a** [torinmb/mediapipe-touchdesigner#52]
Hi, thank you for your hard work on this one. I have one issue to report, I do not seem able to find the spoutcam on the drop-down menu of the Mediapipe container (on windows 11). I have registered the Spoutcam as detailed on the instructions page.

<img width="977" alt="Screenshot 2023-11-01 160707" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/73363953/9dd0433b-c51d-4773-973d-7e594b63ad04">

Also when I load the spoutcam on the VideoDeviceIn TOP it shows up as just black. 
<img width="1243" alt="Screenshot 2023-11-01 160857" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/73363953/9c7b3ece-405b-43f5-8a5b-628958774016">

Any help would be appreciated!

EDIT: I figured the error I am getting on the Mediapipe container might be enlightening:
<img width="992" alt="Screenshot 2023-11-01 161414" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/73363953/61f9c621-3ec6-47c1-a3ad-bb75b188834a">

**Comment by domisjustanumber** [comment]
Hi @tasos-a thanks for the kind words :)

We just released a new version that fixes a number of issues around webcams loading and provides us with more useful debug when things go wrong. Would you be able to try it out and see what happens? https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.3.2

Also FYI on that Video Device In chain at the bottom of the project there - the idea for that chain is:

Select your real webcam in Video Device In > Syphon Spout OUT > SpoutCam > SpoutCam virtual webcam is selected in the MediaPipe component.

If you select SpoutCam as the source in the Video Device In TOP there, it's a circular loop sending itself to itself, so will only show black.

**Comment by tasos-a** [comment]
Hi @domisjustanumber thanks for the quick reply! I just tried the latest release you linked me to and still get the same errors. I tried using my real webcam on the Video Device In chain and indeed I got the camera's input but still no spoutcam at the drop down menu of MediaPipe container.

**Comment by tasos-a** [comment]
Ok so i got it to work by replacing the MediaPipe container inside MediaPipe toe with MediaPipe tox. I still get errors but it works.

**Comment by joansc** [comment]
Hello all, wow thanks for the fast response and debugging. I confirm that with the latest release it works straight out of the box. Thanks and congrats for this amazing tool!

**Comment by domisjustanumber** [comment]
Sounds like you got it working ok, so I'm going to close this. Please re-open it if you need any more help
